### ISSUE TITLE
More tests?

### ISSUE THREAD

**Issue by digitaldonkey** [web3p/rlp#13]
I have a hard time getting together your encoding and other tests. E.g: 
https://github.com/ethereum/web3.js/blob/cd1cfd9db6cacb494884a1824f8562c6440f85df/test/coder.decodeParam.js

What types are currently supported?

**Comment by sc0Vu** [comment]
Contract data and types are decoded in web3 solidity type not in rlp, so I close this issue.
Thanks for report.
